DROP TABLE post_album;
DROP TABLE post_ad;
DROP TABLE likes;
DROP TABLE comment;
DROP TABLE post;
DROP TABLE favorite_albums;
DROP INDEX album_author_title_idx;
DROP TABLE album;
DROP TABLE post_resource;
